aws_region      = "us-east-2"
key_name        = "ohio-keypair"
instance_type   = "t2.micro"
db_username     = "admin"
db_password     = "password"
s3_bucket_name  = "prestashop-media"
ami_id          = "ami-077b630ef539aa0b5"
